### ISSUE TITLE
Upgrading from 1.0.0

### ISSUE THREAD

**Issue by nmg196** [pacal/NPoco_Identity_Provider#2]
Hi,
I've noticed that NuGet doesn't show that you can update 1.0.0 to any more recent version. It seems the package ID has changed and 1.0.2 is called a different name.

If I'm upgrading from 1.0.0 what do I need to change?  Currently I get a compilation error saying "type or namespace "DataProvider" could not be found".

Thanks,
Nick

**Comment by pacal** [comment]
Hi, it looks like some one has the same implementation as I do with almost the same name as this project. They are at 1.0.2
https://github.com/izio/NPoco.Identity.Provider

It is a totally different project so the again, the interface is different.
